[versions]
kotlin = "1.9.23"
compose = "1.6.0"
compose-plugin = "1.5.8.1"
dokka = "1.9.20"
nmcp = "0.0.4"
detekt = "1.23.5"
npm-publish = "3.4.2"
kilua = "0.0.1"
kilua-rpc = "0.0.2-SNAPSHOT"
kotlinx-atomicfu = "0.23.2"
kotlinx-coroutines = "1.8.0"
kotlinx-serialization = "1.6.3"
kotlinx-datetime = "0.6.0-RC.2"
ktor = "2.3.9"
koin-annotations = "1.3.1"
logback = "1.5.3"
npm-kilua-assets = "0.0.7"
css-loader = "6.10.0"
style-loader = "3.3.4"
imports-loader = "5.0.0"
splitjs = "1.6.5"
html-differ = "1.4.0"
popperjs-core = "2.11.8"
bootstrap = "5.3.3"
bootstrap-icons = "1.11.3"
fontawesome = "6.5.1"
trix = "2.0.10"
toastify = "1.12.0"
tempus-dominus = "6.9.5"
tom-select = "2.3.1"
imask = "7.5.0"
tabulator = "5.6.1"
rsup-progress = "3.2.0"

[libraries]
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinx-atomicfu" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kilua-rpc-core = { module = "dev.kilua:kilua-rpc-core", version.ref = "kilua-rpc" }
kilua-rpc-ktor-koin = { module = "dev.kilua:kilua-rpc-ktor-koin", version.ref = "kilua-rpc" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-compression = { module = "io.ktor:ktor-server-compression", version.ref = "ktor" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
npm-publish = { id = "dev.petuska.npm.publish", version.ref = "npm-publish" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
nmcp = { id = "com.gradleup.nmcp", version.ref = "nmcp" }
kilua-rpc = { id = "dev.kilua.rpc", version.ref = "kilua-rpc" }
