[versions]
kotlin = "1.9.23"
compose = "1.6.1"
compose-plugin = "1.5.10.1"
dokka = "1.9.20"
nmcp = "0.0.4"
detekt = "1.23.6"
npm-publish = "3.4.2"
gradle-plugin-publish = "1.2.1"
kilua = "0.0.1"
kilua-published = "0.0.1-SNAPSHOT"
kilua-rpc = "0.0.4"
kotlinx-atomicfu = "0.23.2"
kotlinx-coroutines = "1.8.1-Beta"
kotlinx-serialization = "1.6.3"
kotlinx-datetime = "0.6.0-RC.2"
javalin = "6.1.3"
jooby = "3.0.8"
ktor = "2.3.9"
koin-annotations = "1.3.1"
spring-boot = "3.2.4"
spring-dependency-management = "1.1.4"
vertx = "4.5.7"
vertx-plugin = "1.4.0"
shadow = "8.1.1"
logback = "1.5.3"
tomlj = "1.1.1"
npm-kilua-assets = "0.0.7"
css-loader = "6.10.0"
style-loader = "3.3.4"
imports-loader = "5.0.0"
splitjs = "1.6.5"
html-differ = "1.4.0"
popperjs-core = "2.11.8"
bootstrap = "5.3.3"
bootstrap-icons = "1.11.3"
fontawesome = "6.5.1"
trix = "2.1.0"
toastify = "1.12.0"
tempus-dominus = "6.9.6"
tom-select = "2.3.1"
imask = "7.5.0"
tabulator = "6.2.0"
rsup-progress = "3.2.0"

[libraries]
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "kotlinx-atomicfu" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
javalin = { module = "io.javalin:javalin", version.ref = "javalin" }
jooby-kotlin = { module = "io.jooby:jooby-kotlin", version.ref = "jooby" }
jooby-netty = { module = "io.jooby:jooby-netty", version.ref = "jooby" }
kilua-rpc-core = { module = "dev.kilua:kilua-rpc-core", version.ref = "kilua-rpc" }
kilua-rpc-ktor-koin = { module = "dev.kilua:kilua-rpc-ktor-koin", version.ref = "kilua-rpc" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-compression = { module = "io.ktor:ktor-server-compression", version.ref = "ktor" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin-annotations" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-apache = { module = "io.ktor:ktor-client-apache", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
kilua-rpc-spring-boot = { module = "dev.kilua:kilua-rpc-spring-boot", version.ref = "kilua-rpc" }
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter", version.ref = "spring-boot" }
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux", version.ref = "spring-boot" }
vertx-web = { module = "io.vertx:vertx-web", version.ref = "vertx" }
vertx-lang-kotlin = { module = "io.vertx:vertx-lang-kotlin", version.ref = "vertx" }
vertx-lang-kotlin-coroutines = { module = "io.vertx:vertx-lang-kotlin-coroutines", version.ref = "vertx" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
tomlj = { module = "org.tomlj:tomlj", version.ref = "tomlj" }

[plugins]
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
npm-publish = { id = "dev.petuska.npm.publish", version.ref = "npm-publish" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
nmcp = { id = "com.gradleup.nmcp", version.ref = "nmcp" }
kilua-rpc = { id = "dev.kilua.rpc", version.ref = "kilua-rpc" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-plugin-publish" }
kilua = { id = "dev.kilua", version.ref = "kilua-published" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
jooby = { id = "io.jooby.run", version.ref = "jooby" }
vertx = { id = "io.vertx.vertx-plugin", version.ref = "vertx-plugin" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
